### ISSUE TITLE
[2주차] 변수

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#13]

**Comment by yht0827** [comment]
URL: https://ht.oopy.io/f90e4e0c-b501-4533-92e6-e26d1524a614

**Comment by junghyun100** [comment]
공통 LINK : https://www.notion.so/2-57fdeaabe1b447f0b31394236e61fb82
심화 LINK : https://www.notion.so/2-JVM-d7fc890790ba4bff850af77baed443d5

**Comment by truehong** [comment]
link : https://truehong.tistory.com/55

**Comment by pa324** [comment]
https://github.com/code-chobo-study/java-study/blob/master/2%EC%A3%BC%EC%B0%A8/sangypark/2%EC%A3%BC%EC%B0%A8-%EB%A9%94%EB%AA%A8%EB%A6%AC.md

**Comment by sangyyypark** [comment]
https://github.com/code-chobo-study/java-study/blob/master/2%EC%A3%BC%EC%B0%A8/sangypark/2%EC%A3%BC%EC%B0%A8-%EB%B3%80%EC%88%98.md
