### ISSUE TITLE
[4주차] 자바 다차원 배열을 메모리 관점에서 조사

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#15]
속으로 주소에 할당되는데 자바에서는 new로 만드는데 여기서 실제 자바는 2차원 배열이 2차원배열이 아니라고 하던데 이거에 대해서 한번 차이랑 메모리같은거 조사

**Comment by yht0827** [comment]
URL: https://ht.oopy.io/1671bd88-1d3c-4459-8534-b37de6e84479
