### ISSUE TITLE
[4주차] 배열

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#19]
[4주차] 배열 기본내용 정리

**Comment by yht0827** [comment]
URL: https://ht.oopy.io/2bd0104f-fb0b-4819-b05b-8dd47584e9fd

**Comment by sangyyypark** [comment]
https://syundev.tistory.com/286

**Comment by junghyun100** [comment]
https://www.notion.so/4-a33b1ec966c14acebd8232cc99252f39

**Comment by truehong** [comment]
https://github.com/truehong/books/blob/master/%EC%9E%90%EB%B0%94%EC%9D%98%20%EC%A0%95%EC%84%9D/chapter/Chapter5-%EB%B0%B0%EC%97%B4.md
