### ISSUE TITLE
[5주차] 객체지향 프로그래밍 1

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#20]

**Comment by sangyyypark** [comment]
https://stream-may-e52.notion.site/ff04c7cc9f014f24a78b9fe949bf5fde

**Comment by junghyun100** [comment]
https://www.notion.so/5-c9fd30d6e2af4f3f8b564c01366aa252

**Comment by yht0827** [comment]
url: https://ht.oopy.io/8e421ef2-2d99-45ae-8668-5b3997027f84
