### ISSUE TITLE
[6주차] 객체지향 프로그래밍 2

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#25]

**Comment by truehong** [comment]
https://github.com/truehong/books/blob/master/%EC%9E%90%EB%B0%94%EC%9D%98%20%EC%A0%95%EC%84%9D/chapter/Chapter7-%EA%B0%9D%EC%B2%B4%EC%A7%80%ED%96%A5%20%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D2.md

**Comment by junghyun100** [comment]
링크 : https://local-radon-9e4.notion.site/6-2-b517719122ce49799bc1f9750c7cfa6f

**Comment by yht0827** [comment]
url: https://ht.oopy.io/4fd97584-ec0b-4bed-b533-5ffdebfda7bb

**Comment by sangyyypark** [comment]
https://stream-may-e52.notion.site/2-723425692ec6450a950a6e60b591abc6
