### ISSUE TITLE
[7주차] 예외처리 & 자바 Lang패키지와 유용한 클래스 & 날짜와 시간 / 형식화

### ISSUE THREAD

**Issue by junghyun100** [code-chobo-study/java-study#34]

**Comment by sangyyypark** [comment]
https://stream-may-e52.notion.site/8-Lang-14bc69f715d74a679fee7a8c2d54fda0

**Comment by truehong** [comment]
https://github.com/truehong/books/blob/master/%EC%9E%90%EB%B0%94%EC%9D%98%20%EC%A0%95%EC%84%9D/chapter/Chapter8-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC.md

**Comment by yht0827** [comment]
예외처리: https://ht.oopy.io/015aa3ba-293d-4bd9-a742-fbab100d526a
lang패키지와 유용한 클래스: https://ht.oopy.io/87708288-c37c-4038-bd7b-a34406fdb65d
날짜, 시간 관련 클래스: https://ht.oopy.io/b2de21b7-c98b-4a5d-8b03-7ccd83ca2319

**Comment by junghyun100** [comment]
https://www.notion.so/7-Lang-0fc68ed14aa04c81a344b46b389fee0f
