### ISSUE TITLE
[10주차] generic, enum, annotation

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#43]
[10주차] generic, enum, annotation

**Comment by sangyyypark** [comment]
https://stream-may-e52.notion.site/Generic-Annotation-Enum-18e2019bd4634a73a3673c3f70d2c0a0

**Comment by yht0827** [comment]
enum: https://ht.oopy.io/086b4995-e83b-4225-80fe-e812eddc2a33
generic: https://ht.oopy.io/2dd42ca4-75ee-4056-b9a1-789fa1fbcf58
annotation: https://ht.oopy.io/d12124b6-9d2d-4051-b93f-71e4db68306a

**Comment by junghyun100** [comment]
https://local-radon-9e4.notion.site/10-enum-12cdb1ad2abf4252995d74902991bb67
