### ISSUE TITLE
[1주차] JIT 코드캐시와 메서드캐시

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#7]

**Comment by junghyun100** [comment]
<img src="https://user-images.githubusercontent.com/22961251/103324980-846d0900-4a41-11eb-9a9a-cfc9e16ce227.png">

출처 : https://dailyworker.github.io/fundamental-JVM-classloader/

자바 컴파일러에 의해 생성된 자바 바이트 코드를 JVM의 클래스 로더 시스템을 활용하여 **메모리에 적재한 후**에 실행 엔진에서 런타임 시 인터프리터와 JIT 컴파일러를 활용하여 실제 자바 바이트 코드 → 네이티브 코드 로 변경하여 실행한다고 보면 된다.

### 위 글을 참고 했을 때, 메모리에 적재할 때 사용하는 것을 메모리 캐시를 활용한다 라고 이야기 하는 것으로 보입니다.

코드 캐시(Code Cache)는 네이티브 코드로 번역된 코드들이 저장됩니다.



* 추가로 JIT 컴파일러 관련 해서 자세히 작성된 블로그가 있어서 링크남깁니다.

LINK : https://velog.io/@kwj1270/JIT-Compiler
