### ISSUE TITLE
[2주차] java에서 메모리가 할당될때 실제 메모리상에 어떻게 올라갈까?

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#8]

**Comment by sangyyypark** [comment]
기본형 타입과 참조형 타입이 메모리에 올라가는 과정 등등

**Comment by truehong** [comment]
link : https://truehong.tistory.com/54

**Comment by sangyyypark** [comment]
https://github.com/code-chobo-study/java-study/blob/master/2%EC%A3%BC%EC%B0%A8/sangypark/2%EC%A3%BC%EC%B0%A8-%EB%A9%94%EB%AA%A8%EB%A6%AC.md
