### ISSUE TITLE
[2주차] jvm에서 스택프레임은 무엇이고 어떻게 사용되는걸까?

### ISSUE THREAD

**Issue by sangyyypark** [code-chobo-study/java-study#9]

**Comment by junghyun100** [comment]
LINK : https://www.notion.so/2-JVM-d7fc890790ba4bff850af77baed443d5?showMoveTo=true&saveParent=true

**Comment by yht0827** [comment]
url: https://ht.oopy.io/e4ad0027-9d1c-4d80-b4b7-8a026e942920
